[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['lib']
test = 'contracts/test'
cache_path = 'cache_forge'
via_ir = true
fs_permissions = [{ access = "read", path = "./router-config.json"}]

[rpc_endpoints]
base = "https://mainnet.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }

[profile.ci]
fuzz = { runs = 10000 }
