[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib', 'v3-periphery']
test = 'contracts/test'
cache_path  = 'cache_forge'

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/z0-B5SXVWQSfl0XY9KLWa7kLRc7sl44p"

[profile.mainnet]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib', 'v3-periphery']
test = 'contracts/test'
cache_path  = 'cache_forge'
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/z0-B5SXVWQSfl0XY9KLWa7kLRc7sl44p"
