[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib', 'v3-periphery']
test = 'contracts/test'
cache_path  = 'cache_forge'
remappings = [
    'aerodrome-v3/=lib/aerodrome-v3/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    'v3-periphery/=lib/v3-periphery/',
    'v3-core/=lib/v3-core/',
    'pancake-v3-core/=lib/pancake-v3-contracts/projects/v3-core/contracts/',
    'pancake-v3-periphery/=lib/pancake-v3-contracts/projects/v3-periphery/contracts/',
    'sushiswap-v3-contracts/=lib/sushiswap-v3-contracts/protocols/sushiswap/contracts/v3/',
    '@uniswap/v3-core/=lib/v3-core/'
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/z0-B5SXVWQSfl0XY9KLWa7kLRc7sl44p"

[profile.mainnet]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib', 'v3-periphery']
test = 'contracts/test'
cache_path  = 'cache_forge'
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/z0-B5SXVWQSfl0XY9KLWa7kLRc7sl44p"
remappings = [
    'aerodrome-v3/=lib/aerodrome-v3/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    'v3-periphery/=lib/v3-periphery/',
    'v3-core/=lib/v3-core/',
    'pancake-v3-core/=lib/pancake-v3-contracts/projects/v3-core/contracts/',
    'pancake-v3-periphery/=lib/pancake-v3-contracts/projects/v3-periphery/contracts/',
    'sushiswap-v3-contracts/=lib/sushiswap-v3-contracts/protocols/sushiswap/contracts/v3/',
    '@uniswap/v3-core/=lib/v3-core/'
]
