[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib', 'v3-periphery']
test = 'contracts/test'
cache_path  = 'cache_forge'

[rpc_endpoints]
base = "https://base.publicnode.com"

[profile.swift]
output_path = "swift/"
